In [27]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from collections import Counter

In [2]:
df_ads = pd.read_csv('Social_Network_Ads.csv')
df_ads.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
df_ads_final = df_ads.drop(['User ID'], axis = 1)
df_ads_final.head()

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [5]:
encoder = LabelEncoder()
df_ads_final['Gender'] = encoder.fit_transform(df_ads_final['Gender'])
df_ads_final.head()

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_x = df_ads_final.iloc[:,0:3].values
df_y = df_ads_final.iloc[:,-1].values
df_x, df_y

(array([[    1,    19, 19000],
        [    1,    35, 20000],
        [    0,    26, 43000],
        ...,
        [    0,    50, 20000],
        [    1,    36, 33000],
        [    0,    49, 36000]]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_x, df_y, test_size = 0.2, random_state = 41)

In [19]:
df_ads_scaled_train = scaler.fit_transform(X_train)
df_ads_scaled_test = scaler.transform(X_test)
df_ads_scaled_train, df_ads_scaled_test

(array([[-0.95118973, -0.06599205,  2.21413759],
        [-0.95118973, -0.64988486,  0.0381701 ],
        [ 1.05131497,  0.42058529, -0.1359073 ],
        [ 1.05131497,  0.32326982, -0.7161653 ],
        [-0.95118973,  0.42058529,  0.58941519],
        [-0.95118973, -1.42840861, -0.6291266 ],
        [ 1.05131497, -1.81767048, -1.4705007 ],
        [ 1.05131497, -0.06599205,  2.15611179],
        [ 1.05131497, -1.52572408, -1.4995136 ],
        [ 1.05131497, -0.16330752, -1.0643201 ],
        [-0.95118973, -1.72035501, -0.9772814 ],
        [-0.95118973, -0.16330752, -0.1939331 ],
        [ 1.05131497, -0.16330752,  1.40177639],
        [-0.95118973, -0.26062299, -0.2809718 ],
        [ 1.05131497,  2.17226372, -0.803204  ],
        [ 1.05131497,  1.97763278,  2.15611179],
        [ 1.05131497, -0.74720033,  0.56040229],
        [-0.95118973, -1.72035501, -1.3544491 ],
        [ 1.05131497, -0.26062299, -1.383462  ],
        [-0.95118973,  1.0044781 ,  1.98203439],
        [ 1.05131497

In [20]:
from sklearn.neighbors import KNeighborsClassifier

In [21]:
knn_clf = KNeighborsClassifier(n_neighbors = 5)
knn_clf.fit(X_train, y_train)
y_pred = knn_clf.predict(X_test)

In [22]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8375

### KNN From Scratch

In [36]:
class Knn:
    def __init__(self,k=5):
        self.n_neighbors = k
        self.X_train = None
        self.y_train = None
        self.X_test = None
        
    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train
    
    
    def calculate_distance(self, point_a, point_b):
        return np.linalg.norm(point_a - point_b)
    
    def majority_count(self, neighbors):
        votes = []
        for i in neighbors:
            #since i here is not a number and a list containing the distance as well as the index therefore
            #using i[0] to get the index value from the list
            votes.append(self.y_train[i[0]])
        votes = Counter(votes)
        return votes.most_common()[0][0]
        
        
    def predict(self, X_test):
#         self.X_test = X_test
        y_pred = []
        for i in X_test:
            distances = []
            #calculate distance with each training point
            for j in self.X_train:
                distances.append(self.calculate_distance(i,j))
            #what enumerate does is that it brings in the index position as well along with the distance value
            top_n_neighbors = sorted(list(enumerate(distances)), key = lambda x:x[1])[0:self.n_neighbors]
            label = self.majority_count(top_n_neighbors)
            y_pred.append(label)
            
        return np.array(y_pred)
                

In [37]:
clf_knn = Knn()
clf_knn.fit(X_train, y_train)

In [38]:
y_pred_new = clf_knn.predict(X_test)

In [39]:
accuracy_score(y_test, y_pred_new)

0.8375